# Generated by Django 5.2.3 on 2025-06-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.topico')),
            ],
        ),
    ]
