# Generated by Django 5.2.3 on 2025-07-04 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_registrar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrar',
        ),
        migrations.AddField(
            model_name='assunto',
            name='data_de_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
