# Generated by Django 5.2.3 on 2025-07-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_registrar_assunto_data_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='usuario',
            field=models.TextField(default='Anonimo'),
            preserve_default=False,
        ),
    ]
